`include "autogenerated.sv"

module mdf_tb;

  logic clk;
  logic rst;
  rns_t a;
  rns_t b;
  out_t out;

  localparam int unsigned RNS_RANGE = `MODULI_0 * `MODULI_1 * `MODULI_2;
  localparam int unsigned MAX_VALUE = RNS_RANGE - 1;

  mdf dut (
      .out(out),
      .clk(clk),
      .rst(rst),
      .a  (a),
      .b  (b)
  );

  always #5 clk = ~clk;

  task automatic scalar_to_rns(input int unsigned value, output rns_t encoded);
    int unsigned residue;

    residue = value % int'(`MODULI_0);
    encoded.first = residue[`BITS_PER_RESIDUE_0-1:0];
    residue = value % int'(`MODULI_1);
    encoded.second = residue[`BITS_PER_RESIDUE_1-1:0];
    residue = value % int'(`MODULI_2);
    encoded.third = residue[`BITS_PER_RESIDUE_2-1:0];
  endtask

  function automatic out_t expected_cmp(input int unsigned lhs, input int unsigned rhs);
    if (lhs < rhs) expected_cmp = 3'b100;
    else if (lhs > rhs) expected_cmp = 3'b001;
    else expected_cmp = 3'b010;
  endfunction

  initial begin
    int unsigned i;
    int unsigned j;
    out_t expected;

    clk = 1'b0;
    rst = 1'b1;
    a   = '0;
    b   = '0;

    repeat (2) @(posedge clk);
    rst = 1'b0;

    for (i = 1; i <= MAX_VALUE; i++) begin
      for (j = 1; j <= MAX_VALUE; j++) begin
        @(negedge clk);
        scalar_to_rns(i, a);
        scalar_to_rns(j, b);

        @(posedge clk);
        #1;
        expected = expected_cmp(i, j);
        assert (out === expected)
        else
          $fatal(
              1,
              "Comparison mismatch for i=%0d j=%0d: got lt=%0b eq=%0b gt=%0b, expected lt=%0b eq=%0b gt=%0b",
              i,
              j,
              out.lt,
              out.eq,
              out.gt,
              expected.lt,
              expected.eq,
              expected.gt
          );
      end
    end

    $display("mdf_tb: PASS. Checked all pairs in [1, %0d].", MAX_VALUE);
    $finish;
  end

endmodule
