// file autogenerated by `generate_LUTS.py`, do not modify
`ifndef AUTOGENERATED_SV
`define AUTOGENERATED_SV
`define BITS 14
`define MODULI_0 13
`define MODULI_1 15
`define MODULI_2 17
`define QUOTIENTS_0 255
`define QUOTIENTS_1 221
`define QUOTIENTS_2 195
`define SUM_OF_QUOTIENTS 671
`define K_0 6300
`define K_1 12014
`define K_2 14456
`define BITS_PER_RESIDUE_0 4
`define BITS_PER_RESIDUE_1 4
`define BITS_PER_RESIDUE_2 5
`endif
