// file autogenerated by generate_LUTs.py, do not modify
package autogenerated;
localparam int bits = 47;
localparam int moduli_0 = 2;
localparam int moduli_1 = 3;
localparam int moduli_2 = 11;
localparam int moduli_3 = 23;
localparam int moduli_4 = 31;
localparam int moduli_5 = 47057;
localparam int quotients_0 = 1107204153;
localparam int quotients_1 = 738136102;
localparam int quotients_2 = 201309846;
localparam int quotients_3 = 96278622;
localparam int quotients_4 = 71432526;
localparam int quotients_5 = 47058;
localparam int sum_of_quotients = 2214408307;
localparam [bits-1:0] k_0 = 70368744145887;
localparam [bits-1:0] k_1 = 46912496097258;
localparam [bits-1:0] k_2 = 12794317117434;
localparam [bits-1:0] k_3 = 6119021230078;
localparam [bits-1:0] k_4 = 4539918977154;
localparam [bits-1:0] k_5 = 2990787520;
localparam int bits_per_residue_0 = 1;
localparam int bits_per_residue_1 = 2;
localparam int bits_per_residue_2 = 4;
localparam int bits_per_residue_3 = 5;
localparam int bits_per_residue_4 = 5;
localparam int bits_per_residue_5 = 16;
endpackage
