// file autogenerated by `generate_LUTS.py`, do not modify
package autogenerated;
localparam int bits = 14;
localparam int moduli_0 = 13;
localparam int moduli_1 = 15;
localparam int moduli_2 = 17;
localparam int quotients_0 = 255;
localparam int quotients_1 = 221;
localparam int quotients_2 = 195;
localparam int sum_of_quotients = 671;
localparam [bits-1:0] k_0 = 6300;
localparam [bits-1:0] k_1 = 12014;
localparam [bits-1:0] k_2 = 14456;
localparam int bits_per_residue_0 = 4;
localparam int bits_per_residue_1 = 4;
localparam int bits_per_residue_2 = 5;
endpackage
