import sys
from math import prod, gcd, log2, ceil
from itertools import combinations
from pathlib import Path

def all_moduli_coprime(moduli: [int]) -> bool:
    for x, y in combinations(moduli, 2):
        if gcd(x, y) != 1:
            return False

    return True

def generate_data(moduli: [int]):
    if not all_moduli_coprime(moduli):
        print("Error: moduli are not coprime")
        return

    n = len(moduli)
    dynamic_range = prod(moduli)
    quotients = [dynamic_range // m_i for m_i in moduli]
    sum_of_quotients = sum(quotients)

    bits_per_residue = [ceil(log2(m_i)) for m_i in moduli]
    bits = ceil(log2((max(moduli) - 1) * sum_of_quotients))

    if bits > 32:
        print("Error: size values exceed 32 bits, currently unsupported")
        return

    k = [ceil(2**bits * (-pow(m_i, -1, sum_of_quotients) % sum_of_quotients) / sum_of_quotients) for m_i in moduli]

    target = Path(__file__).resolve().parent / "autogenerated.sv"

    with open(target, "w") as f:
        print("// file autogenerated by `generate_LUTS.py`, do not modify", file=f)
        print("`ifndef AUTOGENERATED_SV", file=f)
        print("`define AUTOGENERATED_SV", file=f)
        print(f"`define BITS {bits}", file=f)
        for i, val in enumerate(moduli):
            print(f"`define MODULI_{i} {val}", file=f)
        for i, val in enumerate(quotients):
            print(f"`define QUOTIENTS_{i} {val}", file=f)
        print(f"`define SUM_OF_QUOTIENTS {sum_of_quotients}", file=f)
        for i, val in enumerate(k):
            print(f"`define K_{i} {val}", file=f)
        for i, val in enumerate(bits_per_residue):
            print(f"`define BITS_PER_RESIDUE_{i} {val}", file=f)
        print("`endif", file=f)
    
if len(sys.argv) > 1:
    if len(sys.argv) != 4:
        print("Error: please supply exactly three moduli")
        exit(1)
    nums = [int(x) for x in sys.argv[1:]]
else:
    nums = [13, 15, 17]

generate_data(nums)

print("Done.")
