import sys
from math import prod, gcd, log2, ceil
from itertools import combinations
from pathlib import Path


def all_moduli_coprime(moduli):
    for x, y in combinations(moduli, 2):
        if gcd(x, y) != 1:
            return False
    return True


def generate_data(moduli):
    if not all_moduli_coprime(moduli):
        print("Error: moduli are not coprime")
        return

    n = len(moduli)
    dynamic_range = prod(moduli)
    quotients = [dynamic_range // m for m in moduli]
    sum_of_quotients = sum(quotients)

    bits_per_residue = [ceil(log2(m)) for m in moduli]
    bits = ceil(log2((max(moduli) - 1) * sum_of_quotients))

    if bits > 32:
        print("Warning: bits exceeds 32, values may need wide literals")

    k = [
        ceil(2**bits * (-pow(m, -1, sum_of_quotients) % sum_of_quotients) / sum_of_quotients)
        for m in moduli
    ]

    target = Path(__file__).resolve().parent / "autogenerated.sv"

    with open(target, "w") as f:
        print("// file autogenerated by generate_LUTs.py, do not modify", file=f)
        print(f"`define AUTOG_BITS {bits}", file=f)
        for i, val in enumerate(moduli):
            print(f"`define AUTOG_MODULI_{i} {val}", file=f)
        for i, val in enumerate(quotients):
            print(f"`define AUTOG_QUOTIENTS_{i} {val}", file=f)
        print(f"`define AUTOG_SUM_OF_QUOTIENTS {sum_of_quotients}", file=f)
        for i, val in enumerate(k):
            print(f"`define AUTOG_K_{i} {val}", file=f)
        for i, val in enumerate(bits_per_residue):
            print(f"`define AUTOG_BITS_PER_RESIDUE_{i} {val}", file=f)


if len(sys.argv) > 1:
    if len(sys.argv) < 4:
        print("Error: please supply at least three moduli")
        exit(1)
    nums = [int(x) for x in sys.argv[1:]]
else:
    nums = [2, 3, 11, 23, 31, 47057]

generate_data(nums)

print("Done.")
