`include "rns_types.sv"
import autogenerated::*;

module mdf (
    output out_t out,
    input  rns_t a,
    input  rns_t b
);

  logic [bits-1:0] a0, a1, a2, a3, a4, a5;
  logic [bits-1:0] b0, b1, b2, b3, b4, b5;
  logic [bits-1:0] D_a, D_b;

  assign a0 = a.first * k_0;
  assign a1 = a.second * k_1;
  assign a2 = a.third * k_2;
  assign a3 = a.fourth * k_3;
  assign a4 = a.fifth * k_4;
  assign a5 = a.sixth * k_5;

  assign b0 = b.first * k_0;
  assign b1 = b.second * k_1;
  assign b2 = b.third * k_2;
  assign b3 = b.fourth * k_3;
  assign b4 = b.fifth * k_4;
  assign b5 = b.sixth * k_5;

  assign D_a = (a0 + a1) + (a2 + a3) + (a4 + a5);
  assign D_b = (b0 + b1) + (b2 + b3) + (b4 + b5);

  assign out = D_a < D_b ? 3'b100 : (D_a > D_b ? 3'b001 : 3'b010);

endmodule
