`include "rns_types.sv"
`include "autogenerated.sv"

module mdf (
    output out_t out,
    input  rns_t a,
    input  rns_t b
);

  logic [`AUTOG_BITS-1:0] a0, a1, a2, a3, a4, a5;
  logic [`AUTOG_BITS-1:0] b0, b1, b2, b3, b4, b5;
  logic [`AUTOG_BITS-1:0] D_a, D_b;

  assign a0 = a.first * `AUTOG_K_0;
  assign a1 = a.second * `AUTOG_K_1;
  assign a2 = a.third * `AUTOG_K_2;
  assign a3 = a.fourth * `AUTOG_K_3;
  assign a4 = a.fifth * `AUTOG_K_4;
  assign a5 = a.sixth * `AUTOG_K_5;

  assign b0 = b.first * `AUTOG_K_0;
  assign b1 = b.second * `AUTOG_K_1;
  assign b2 = b.third * `AUTOG_K_2;
  assign b3 = b.fourth * `AUTOG_K_3;
  assign b4 = b.fifth * `AUTOG_K_4;
  assign b5 = b.sixth * `AUTOG_K_5;

  assign D_a = (a0 + a1) + (a2 + a3) + (a4 + a5);
  assign D_b = (b0 + b1) + (b2 + b3) + (b4 + b5);

  assign out = D_a < D_b ? 3'b100 : (D_a > D_b ? 3'b001 : 3'b010);

endmodule
