`include "autogenerated.sv"

typedef struct packed {
  logic lt;
  logic eq;
  logic gt;
} out_t;

typedef struct packed {
  logic [`BITS_PER_RESIDUE_0-1:0] first;
  logic [`BITS_PER_RESIDUE_1-1:0] second;
  logic [`BITS_PER_RESIDUE_2-1:0] third;
} rns_t;

module mdf (
    output out_t out,
    input  logic clk,
    input  logic rst,
    input  rns_t a,
    input  rns_t b
);

  logic [`BITS-1:0] D_a, D_b;
  out_t out_next;

  assign D_a = (a.first * `K_0 + a.second * `K_1 + a.third * `K_2);
  assign D_b = (b.first * `K_0 + b.second * `K_1 + b.third * `K_2);
  assign out_next = D_a < D_b ? 3'b100 : (D_a > D_b ? 3'b001 : 3'b010);

  always_ff @(posedge clk) begin
    if (rst) out <= 0;
    else out <= out_next;
  end

endmodule
