`include "rns_types.sv"
`include "autogenerated.sv"

/* verilator lint_off WIDTHEXPAND */
module mdf_tb;

  rns_t a;
  rns_t b;
  out_t out;

  function automatic int get_moduli(input int idx);
    case (idx)
      0: return `AUTOG_MODULI_0;
      1: return `AUTOG_MODULI_1;
      2: return `AUTOG_MODULI_2;
      3: return `AUTOG_MODULI_3;
      4: return `AUTOG_MODULI_4;
      5: return `AUTOG_MODULI_5;
      default: return 0;
    endcase
  endfunction

  localparam [`AUTOG_BITS-1:0] RNS_RANGE = `AUTOG_MODULI_0 * `AUTOG_MODULI_1 * `AUTOG_MODULI_2 * `AUTOG_MODULI_3 * `AUTOG_MODULI_4 * `AUTOG_MODULI_5;
  localparam [`AUTOG_BITS-1:0] MAX_VALUE = RNS_RANGE - 1;

  int unsigned passed;
  int unsigned total;

  mdf dut (
      .out(out),
      .a  (a),
      .b  (b)
  );

  task automatic scalar_to_rns(input logic [`AUTOG_BITS-1:0] value, output rns_t encoded);
    logic [`AUTOG_BITS-1:0] residue;

    residue = value % `AUTOG_MODULI_0;
    encoded.first = residue[`AUTOG_BITS_PER_RESIDUE_0-1:0];
    residue = value % `AUTOG_MODULI_1;
    encoded.second = residue[`AUTOG_BITS_PER_RESIDUE_1-1:0];
    residue = value % `AUTOG_MODULI_2;
    encoded.third = residue[`AUTOG_BITS_PER_RESIDUE_2-1:0];
    residue = value % `AUTOG_MODULI_3;
    encoded.fourth = residue[`AUTOG_BITS_PER_RESIDUE_3-1:0];
    residue = value % `AUTOG_MODULI_4;
    encoded.fifth = residue[`AUTOG_BITS_PER_RESIDUE_4-1:0];
    residue = value % `AUTOG_MODULI_5;
    encoded.sixth = residue[`AUTOG_BITS_PER_RESIDUE_5-1:0];
  endtask

  function automatic out_t expected_cmp(input logic [`AUTOG_BITS-1:0] lhs, input logic [`AUTOG_BITS-1:0] rhs);
    if (lhs < rhs) expected_cmp = 3'b100;
    else if (lhs > rhs) expected_cmp = 3'b001;
    else expected_cmp = 3'b010;
  endfunction

  task automatic check_pair(input logic [`AUTOG_BITS-1:0] i, input logic [`AUTOG_BITS-1:0] j);
    out_t expected;
    begin
      total++;
      scalar_to_rns(i, a);
      scalar_to_rns(j, b);
      #1;
      expected = expected_cmp(i, j);
      assert (out === expected)
      else
        $fatal(
            1,
            "Comparison mismatch for i=%0d j=%0d: got lt=%0b eq=%0b gt=%0b, expected lt=%0b eq=%0b gt=%0b",
            i,
            j,
            out.lt,
            out.eq,
            out.gt,
            expected.lt,
            expected.eq,
            expected.gt
        );
      passed++;
    end
  endtask

  initial begin
    int unsigned i;
    int unsigned j;
    int unsigned idx;
    int unsigned seed;

    logic [`AUTOG_BITS-1:0] wide_i;
    logic [`AUTOG_BITS-1:0] wide_j;

    a   = '0;
    b   = '0;
    passed = 0;
    total  = 0;

    // --- Phase 1: Boundary values ---
    $display("[Phase 1] Testing boundary values...");
    for (i = 0; i < 32; i++) begin
      for (j = 0; j < 32; j++) begin
        check_pair(i, j);
      end
    end

    // --- Phase 2: Power-of-2 edges ---
    $display("[Phase 2] Testing power-of-2 boundaries...");
    begin
      logic [`AUTOG_BITS-1:0] p2_vals[8];
      p2_vals[0] = 1;
      p2_vals[1] = 2;
      p2_vals[2] = 4;
      p2_vals[3] = 16;
      p2_vals[4] = 128;
      p2_vals[5] = 1024;
      p2_vals[6] = 1 << 15;
      p2_vals[7] = 1 << 31;
      for (i = 0; i < 8; i++) begin
        for (j = 0; j < 8; j++) begin
          check_pair(p2_vals[i], p2_vals[j]);
        end
      end
    end

    // --- Phase 3: Values near each modulus boundary ---
    $display("[Phase 3] Testing near-modulus boundaries...");
    begin
      logic [`AUTOG_BITS-1:0] mod_test_vals[24];
      logic [`AUTOG_BITS-1:0] modulus_val;
      idx = 0;
      for (i = 0; i < 6; i++) begin
        modulus_val = get_moduli(i);
        mod_test_vals[idx]   = modulus_val - 1;
        mod_test_vals[idx+1] = modulus_val;
        mod_test_vals[idx+2] = modulus_val + 1;
        idx += 3;
      end
      for (i = 0; i < 24; i++) begin
        for (j = 0; j < 24; j++) begin
          if (mod_test_vals[i] <= MAX_VALUE && mod_test_vals[j] <= MAX_VALUE)
            check_pair(mod_test_vals[i], mod_test_vals[j]);
        end
      end
    end

    // --- Phase 4: Cross-modulus products (Chinese Remainder Theorem corners) ---
    $display("[Phase 4] Testing cross-modulus products...");
    begin
      logic [`AUTOG_BITS-1:0] cross_vals[12];
      cross_vals[0]  = get_moduli(0) * get_moduli(1);
      cross_vals[1]  = get_moduli(1) * get_moduli(2);
      cross_vals[2]  = get_moduli(2) * get_moduli(3);
      cross_vals[3]  = get_moduli(3) * get_moduli(4);
      cross_vals[4]  = get_moduli(4) * get_moduli(5);
      cross_vals[5]  = get_moduli(0) * get_moduli(1) * get_moduli(2);
      cross_vals[6]  = get_moduli(3) * get_moduli(4) * get_moduli(5);
      cross_vals[7]  = MAX_VALUE;
      cross_vals[8]  = MAX_VALUE - 1;
      cross_vals[9]  = MAX_VALUE / 2;
      cross_vals[10] = MAX_VALUE / 3;
      cross_vals[11] = MAX_VALUE / 4;
      for (i = 0; i < 12; i++) begin
        for (j = 0; j < 12; j++) begin
          check_pair(cross_vals[i], cross_vals[j]);
        end
      end
    end

    // --- Phase 5: Systematic stride across full range ---
    $display("[Phase 5] Testing systematic stride...");
    begin
      logic [`AUTOG_BITS-1:0] vals_s[64];
      logic [`AUTOG_BITS-1:0] stride;
      stride = MAX_VALUE / 63;
      for (i = 0; i < 64; i++) begin
        vals_s[i] = i * stride;
        if (vals_s[i] > MAX_VALUE) vals_s[i] = MAX_VALUE;
      end
      for (i = 0; i < 64; i++) begin
        check_pair(vals_s[i], vals_s[i]);
        if (i < 63) check_pair(vals_s[i], vals_s[i + 1]);
        if (i > 0) check_pair(vals_s[i], vals_s[i - 1]);
      end
    end

    // --- Phase 6: All equal pairs across sampled values ---
    $display("[Phase 6] Testing equality across range...");
    begin
      logic [`AUTOG_BITS-1:0] eq_vals[32];
      logic [`AUTOG_BITS-1:0] stride;
      stride = MAX_VALUE / 31;
      for (i = 0; i < 32; i++) begin
        eq_vals[i] = i * stride;
        if (eq_vals[i] > MAX_VALUE) eq_vals[i] = MAX_VALUE;
      end
      for (i = 0; i < 32; i++) begin
        check_pair(eq_vals[i], eq_vals[i]);
      end
    end

    // --- Phase 7: Random pairs ---
    $display("[Phase 7] Testing random pairs...");
    seed = 32'hDEAD_BEEF;
    for (i = 0; i < 10000; i++) begin
      seed = seed ^ (seed << 13);
      seed = seed ^ (seed >> 17);
      seed = seed ^ (seed << 5);
      wide_i = seed % RNS_RANGE;

      seed = seed ^ (seed << 13);
      seed = seed ^ (seed >> 17);
      seed = seed ^ (seed << 5);
      wide_j = seed % RNS_RANGE;

      check_pair(wide_i, wide_j);
    end

    // --- Phase 8: Near-equal random pairs (differ by 1-5) ---
    $display("[Phase 8] Testing near-equal random pairs...");
    seed = 32'hCAFE_BABE;
    for (i = 0; i < 5000; i++) begin
      seed = seed ^ (seed << 13);
      seed = seed ^ (seed >> 17);
      seed = seed ^ (seed << 5);
      wide_i = seed % (RNS_RANGE - 10);

      begin
        logic [`AUTOG_BITS-1:0] diff;
        diff = (seed % 5) + 1;
        check_pair(wide_i, wide_i + diff);
        check_pair(wide_i + diff, wide_i);
      end
    end

    // --- Phase 9: Values at each modulus's max residue ---
    $display("[Phase 9] Testing max residue combinations...");
    begin
      logic [`AUTOG_BITS-1:0] v1, v2, prod;
      for (i = 0; i < 6; i++) begin
        for (j = 0; j < 6; j++) begin
          if (i != j) begin
            prod = 1;
            for (int unsigned k = 0; k < 6; k++) begin
              if (k != i) prod = prod * get_moduli(k);
            end
            v1 = prod - 1;
            if (v1 <= MAX_VALUE) begin
              prod = 1;
              for (int unsigned k = 0; k < 6; k++) begin
                if (k != j) prod = prod * get_moduli(k);
              end
              v2 = prod - 1;
              if (v2 <= MAX_VALUE)
                check_pair(v1, v2);
            end
          end
        end
      end
    end

    $display("mdf_tb: PASS. Checked %0d pairs.", total);
    $finish;
  end

endmodule
