`default_nettype none

`include "autogenerated.sv"

module tt_um_mdf_demo (
    input  wire [7:0] ui_in,
    output wire [7:0] uo_out,
    input  wire [7:0] uio_in,
    output wire [7:0] uio_out,
    output wire [7:0] uio_oe,
    input  wire       ena,
    input  wire       clk,
    input  wire       rst_n
);

  rns_t a;
  rns_t b;
  out_t out;

  assign a.first  = ui_in[`BITS_PER_RESIDUE_0-1:0];
  assign a.second = ui_in[`BITS_PER_RESIDUE_0+`BITS_PER_RESIDUE_1-1:`BITS_PER_RESIDUE_0];
  assign a.third  = 0;

  assign b.first  = uio_in[`BITS_PER_RESIDUE_0-1:0];
  assign b.second = uio_in[`BITS_PER_RESIDUE_0+`BITS_PER_RESIDUE_1-1:`BITS_PER_RESIDUE_0];
  assign b.third  = 0;

  mdf mdf_inst (
    .out (out),
    .clk (clk),
    .rst (~rst_n),
    .a   (a),
    .b   (b)
  );

  assign uo_out[0] = out.lt;
  assign uo_out[1] = out.eq;
  assign uo_out[2] = out.gt;
  assign uo_out[7:3] = 5'b0;
  assign uio_out = 8'b0;
  assign uio_oe  = 8'b0;

  wire _unused = &{ena, 1'b0};

endmodule
