`default_nettype none

`include "rns_types.sv"
`include "autogenerated.sv"

module tt_um_mdf_demo (
    input  wire [7:0] ui_in,
    output wire [7:0] uo_out,
    input  wire [7:0] uio_in,
    output wire [7:0] uio_out,
    output wire [7:0] uio_oe,
    input  wire       ena,
    input  wire       clk,
    input  wire       rst_n
);

  rns_t a;
  rns_t b;
  out_t out_mdf;
  out_t out_phase;
  out_t out;

  assign a.first  = {3'b0, ui_in[0]};
  assign a.second = {2'b0, ui_in[2:1]};
  assign a.third  = {1'b0, ui_in[6:3]};
  assign a.fourth = '0;
  assign a.fifth  = '0;
  assign a.sixth  = '0;

  assign b.first  = {3'b0, uio_in[0]};
  assign b.second = {2'b0, uio_in[2:1]};
  assign b.third  = {1'b0, uio_in[6:3]};
  assign b.fourth = '0;
  assign b.fifth  = '0;
  assign b.sixth  = '0;

  mdf mdf_inst (
    .out (out_mdf),
    .a   (a),
    .b   (b)
  );

  phase_sum phase_sum_inst (
    .out (out_phase),
    .a   (a),
    .b   (b)
  );

  assign out = ui_in[7] ? out_phase : out_mdf;

  assign uo_out[0] = out.lt;
  assign uo_out[1] = out.eq;
  assign uo_out[2] = out.gt;
  assign uo_out[7:3] = 5'b0;
  assign uio_out = 8'b0;
  assign uio_oe  = 8'b0;

  wire _unused = &{ena, clk, rst_n, uio_in[7], 1'b0};

endmodule
